### ISSUE TITLE
Ejercicio 2

### ISSUE THREAD

**Issue by manuelchichi** [DevelopmentSpace/TDP-TP2-2016-Grupo8#1]
Basicamente el diagrama de clases hace una cosa y el programa hace otra.

Que queres que te diga, xdxd

**Comment by agustinCaire** [comment]
Zapata y el cabezon lo que hacen es inicializar ambas cuentas en el constructor de Cuentas con valores definidos ahi.. porque si al constructor le pasas parametros estas cambiando el diagrama.

PD: Me costo un poco sincronizar la nueva rama xd

**Comment by manuelchichi** [comment]
Y es que para mi no tendria sentido que sea con valores fijos. Modiquemos eso de ultima. 

Como lo teniamos antes tampoco respetaba el diagrama.

**Comment by manuelchichi** [comment]
¿Que te parecio lo que hice? ¿Esta buenaso no?
